name: FastAPI CI/CD Pipeline
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true 
    name: Continuous Integration
    timeout-minutes: 15  # Add overall job timeout
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-timeout
        
    - name: Run tests
      timeout-minutes: 5  # Add step timeout
      run: |
        pytest --timeout=30
        
  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    timeout-minutes: 15  # Add deployment timeout
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          source ../venv/bin/activate
          sudo apt-get update
          sudo apt install python3-pip
          pip install -r requirements.txt
          sudo service nginx restart
          
          # Kill any existing uvicorn process
          pkill -f "uvicorn main:app" || true
          
          # Start uvicorn in the background with nohup
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
          
          # Wait a moment and check if the process is running
          sleep 5
          if pgrep -f "uvicorn main:app" > /dev/null; then
            echo "FastAPI application started successfully"
            exit 0
          else
            echo "Failed to start FastAPI application"
            cat app.log
            exit 1
          fi
