name: FastAPI CI/CD Pipeline
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Add explicit timeout
    name: Continuous Integration
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        # Run tests and store the exit code
        pytest tests/ || exit 1
        
  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          source ../venv/bin/activate
          sudo apt-get update
          sudo apt install python3-pip
          pip install -r requirements.txt
          sudo service nginx restart
          
          # Kill existing process if running
          pid=$(lsof -t -i:8000 || true)
          if [ ! -z "$pid" ]; then
            sudo kill -9 $pid || true
          fi
          
          # Start the FastAPI application
          cd /home/ubuntu/fastapi-book-project
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > /home/ubuntu/fastapi.log 2>&1 &
          
          # Wait and verify the application started
          sleep 10
          if curl -s http://localhost:8000/health > /dev/null; then
            echo "FastAPI application started successfully"
            exit 0
          else
            echo "Failed to start FastAPI application"
            cat /home/ubuntu/fastapi.log
            exit 1
          fi
