name: CI and Deployment Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      
      - name: Run Linter
        run: |
          pip install flake8
          flake8 . --max-line-length=100 --exclude=venv

      - name: Run Pytest
        run: pytest --exitfirst --failed-first --disable-warnings || exit 1


  deploy:
    name: Deploy API
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to AWS
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
          DEPLOY_USER: ubuntu
        run: |
          echo "$AWS_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $DEPLOY_USER@$AWS_HOST << 'EOF'
            cd /path/to/your/api
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart your-api-service
          EOF
